apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ca
  namespace: $NAMESPACE
spec:
  isCA: true
  commonName: server-ca
  secretName: server-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: server-ca-issuer
  namespace: $NAMESPACE
spec:
  ca:
    secretName: server-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-ca
  namespace: $NAMESPACE
spec:
  isCA: true
  commonName: client-ca
  secretName: client-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: client-ca-issuer
  namespace: $NAMESPACE
spec:
  ca:
    secretName: client-ca-secret
