
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-nephe-controller-tls
  namespace: nephe-system
spec:
  # Secret names are always required.
  secretName: k3s-nephe-controller-tls-secret

  secretTemplate:
    labels:
      app: antrea

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - system:masters
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: nephe-controller
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - antrea-apiserver.nephe-system.svc.cluster.local
    - antrea-apiserver.nephe-system.svc
  # Issuer references are always required.
  issuerRef:
    name: client-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nephe-controller-serving-auth
  namespace: nephe-system
spec:
  # Secret names are always required.
  secretName: nephe-controller-serving-secret

  secretTemplate:
    labels:
      app: nephe

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - system:masters
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: system:apiserver
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - nephe-controller-service.nephe-system.svc.cluster.local
    - nephe-controller-service.nephe-system.svc
  # Issuer references are always required.
  issuerRef:
    name: server-ca-issuer
    kind: Issuer
    group: cert-manager.io
