apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-admin-tls
spec:
  # Secret names are always required.
  secretName: k3s-admin-tls-secret

  secretTemplate:
    labels:
      app: antrea

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - system:masters
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: system:apiserver
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - k3s-apiserver.nsxaas-antreatest-poc.svc
  # Issuer references are always required.
  issuerRef:
    name: server-ca-issuer
    kind: Issuer
    group: cert-manager.io
