apiVersion: v1
kind: Namespace
metadata:
  name: nephe-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nephe-controller-service
  namespace: nephe-system
spec:
  ports:
  - port: 443
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    kubernetes.io/service-name: nephe-controller-service
  name: nephe-controller-service
  namespace: nephe-system
subsets:
- addresses:
  - ip: 100.66.13.51
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    #cert-manager.io/inject-ca-from: nephe-system/serving-cert
  name: v1alpha1.runtime.cloud.antrea.io
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lRZGdxYTNOYlI3ZzRNMUZxVkFPU2prREFOQmdrcWhraUc5dzBCQVFzRkFEQWQKTVJzd0dRWURWUVFERXhKamJIVnpkR1Z5TFdsemMzVmxjaTEwYkhNd0hoY05Nak13TVRFek1qSTBOVEV3V2hjTgpNamd3TVRFeU1qSTBOVEV3V2pBZE1Sc3dHUVlEVlFRREV4SmpiSFZ6ZEdWeUxXbHpjM1ZsY2kxMGJITXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGtrcU1IUlA5S1BXc1pFekl4UWlVV0pqYzIKSTNXT1RFeENrZnMweDg3Q2oya3kwS3pZaHhZV2NzRC9JWEE2NGxEK05uSm5QVVlYS0JvbmdZZlpqY2NLbnZydQpXbER3dCtVRGowbGdSZnZsY2lpaXE2TlFLN3VQa0lZVVp2TjB2c1QvY0g3a0UzempOZDVJV1FpaW9iTVVZWVBrCklMSnJySlpINTZTTXFtV1ZkeXpKZjdkL1pvNW5BeXVxdjRMRThNZENJZnhEaHgzQjFmNGZNZndVZEhjNHFlRTgKWVQyTXI0dTdneStpb1IxK1hRdTZBSklLOGdlbDFUMkNtUDd2eFp4NEdlaEx6elBXd2lBZTllOC9FT24vL09tRwpPd05KQjFBMEJKcS90bDlxZWs5a3Y4Yms5RGlWMzkzQU9qYzVNaEptQXBPVC8wQ29qVkVOdXJFdi9hS0hBZ01CCkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUV05RMHFzK1ZtK1p1aVE0QUQrclQwS1czVmV6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKM1A5RDZRVgpMRHdWeVNFdWxVWk9KL3BzQVN0V2RJZVJMeDR5WWlvYUp6RzZZSkJCYWRoS1VnS2NmMnREeEFPVk9jY3lZeGxDCnlHWDQvN0xmcllzNWdudTkvNGpQdzlTeDJiNWRKdnhHZDl0Y25JamgzLzJsVEpVR0p1YUNOME1paWc4RHNCdlYKYWdzWUo3YmFFTnpZRVkxRzFROUFLbGxNRXFsTEdDbGRrcnNsdVBUWmhidkp3Z2lJbDlTODc5S1NmZWVLRkpVdwpIR0xXU0JteEhuTmVkRCtHdVFQOTRiNWRHOWtyVk9BRFEzOVpqNzY0L242ZE5INTFEdkNhQkFzVjZ6ekRFZ1VtClowUkdRVTFBeXNSZ0g5VzVOdGcxS0hXODdXUnVZbEF5a3dMcUNIMTNEdm9ZYnF3MFpIZW9FS2Z4U0cvME5vTlMKaVNIcXBLVUNqdXN2UVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  group: runtime.cloud.antrea.io
  groupPriorityMinimum: 100
  service:
    name: nephe-controller-service
    namespace: nephe-system
  version: v1alpha1
  versionPriority: 100
---
